import Image from "next/image";
import Head from "next/head";
import { HomeContainer, HomeContent } from "@/styles/home";
import bannerImg from "@/assets/banner.svg";
import { Search } from "@/components/Search";
import { api } from "@/services/api";
interface responseProp {
  user: {
    login: string;
  };
}

export default function Home() {
  const searchPullRequest = async (prUrl: string) => {
    const match: RegExpMatchArray | null = prUrl.match(
      /https:\/\/github\.com\/([^/]+)\/([^/]+)\/pull\/(\d+)/
    );
    if (match) {
      const owner: string = match[1];
      const repo: string = match[2];
      const pull_number: string = match[3];
      const response = await api
        .get<responseProp>(`/repos/${owner}/${repo}/pulls/${pull_number}`)
        .catch((error) => {
          console.log(error);
        });
      console.log(response?.data.user.login, repo);
      console.log(response);
    } else {
      console.log("Invalid URL");
    }
  };

  return (
    <>
      <Head>
        <title>Pull Snap</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeContainer>
        <HomeContent>
          <Search
            label="Link do Pull Request"
            textButton="Pesquisar"
            action={(url) => searchPullRequest(url)}
          />
          <Image src={bannerImg} alt="" priority />
        </HomeContent>
      </HomeContainer>
    </>
  );
}
