import Image from "next/image";
import Head from "next/head";
// import { Inter } from "next/font/google";
import { HomeContainer, HomeContent } from "@/styles/home";

// const inter = Inter({ subsets: ["latin"] });

import bannerImg from "../assets/banner.svg";
import { Search } from "@/components/Search";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pull Snap</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeContainer>
        <HomeContent>
          <Search />
          <Image src={bannerImg} alt="" priority />
        </HomeContent>
      </HomeContainer>
    </>
  );
}
